TRACKED_STOCKS: Dict[str, Dict[str, Any]] = {
    "RELIANCE": {"name": "Reliance Industries Limited", "marketCap": "₹19.8L Cr", "pe": 28.5},
    "TCS": {"name": "Tata Consultancy Services Limited", "marketCap": "₹15.2L Cr", "pe": 32.1},
    "INFY": {"name": "Infosys Limited", "marketCap": "₹7.1L Cr", "pe": 26.5},
    "HDFCBANK": {"name": "HDFC Bank Limited", "marketCap": "₹11.2L Cr", "pe": 18.2},
    "ICICIBANK": {"name": "ICICI Bank Limited", "marketCap": "₹7.8L Cr", "pe": 17.5},
    "HINDUNILVR": {"name": "Hindustan Unilever Limited", "marketCap": "₹5.8L Cr", "pe": 55.2},
    "BHARTIARTL": {"name": "Bharti Airtel Limited", "marketCap": "₹7.5L Cr", "pe": 65.2},
    "ITC": {"name": "ITC Limited", "marketCap": "₹5.4L Cr", "pe": 26.5},
    "WIPRO": {"name": "Wipro Limited", "marketCap": "₹2.7L Cr", "pe": 22.8},
    "KOTAKBANK": {"name": "Kotak Mahindra Bank Limited", "marketCap": "₹3.5L Cr", "pe": 20.5},
    "AXISBANK": {"name": "Axis Bank Limited", "marketCap": "₹3.4L Cr", "pe": 14.2},
    "MARUTI": {"name": "Maruti Suzuki India Limited", "marketCap": "₹3.9L Cr", "pe": 28.5},
    "TITAN": {"name": "Titan Company Limited", "marketCap": "₹3.2L Cr", "pe": 85.2},
    "ASIANPAINT": {"name": "Asian Paints Limited", "marketCap": "₹2.7L Cr", "pe": 52.5},
    "NESTLEIND": {"name": "Nestle India Limited", "marketCap": "₹2.4L Cr", "pe": 75.2},
    "ULTRACEMCO": {"name": "UltraTech Cement Limited", "marketCap": "₹2.9L Cr", "pe": 42.5},
    "BAJFINANCE": {"name": "Bajaj Finance Limited", "marketCap": "₹4.5L Cr", "pe": 35.2},
    "SUNPHARMA": {"name": "Sun Pharmaceutical Industries Limited", "marketCap": "₹3.9L Cr", "pe": 38.5},
    "LT": {"name": "Larsen & Toubro Limited", "marketCap": "₹5.1L Cr", "pe": 35.2},
    "TECHM": {"name": "Tech Mahindra Limited", "marketCap": "₹1.3L Cr", "pe": 45.2},
    "SBIN": {"name": "State Bank of India", "marketCap": "₹6.9L Cr", "pe": 11.5},
    "TATAMOTORS": {"name": "Tata Motors Limited", "marketCap": "₹3.2L Cr", "pe": 18.5},
    "ADANIENT": {"name": "Adani Enterprises Limited", "marketCap": "₹3.6L Cr", "pe": 95.2},
    "POWERGRID": {"name": "Power Grid Corporation of India", "marketCap": "₹2.7L Cr", "pe": 18.5},
    "NTPC": {"name": "NTPC Limited", "marketCap": "₹3.5L Cr", "pe": 19.5},
    "HCLTECH": {"name": "HCL Technologies Limited", "marketCap": "₹4.2L Cr", "pe": 26.5},
    "ONGC": {"name": "Oil and Natural Gas Corporation", "marketCap": "₹3.6L Cr", "pe": 8.5},
    "COALINDIA": {"name": "Coal India Limited", "marketCap": "₹2.8L Cr", "pe": 9.5},
    "BPCL": {"name": "Bharat Petroleum Corporation Limited", "marketCap": "₹1.4L Cr", "pe": 7.5},
    "JSWSTEEL": {"name": "JSW Steel Limited", "marketCap": "₹2.1L Cr", "pe": 28.5},
    "BANKBARODA": {"name": "Bank of Baroda", "marketCap": "₹1.4L Cr", "pe": 8.5},
    "PNB": {"name": "Punjab National Bank", "marketCap": "₹1.5L Cr", "pe": 15.5},
    "INDUSINDBK": {"name": "IndusInd Bank Limited", "marketCap": "₹1.2L Cr", "pe": 14.5},
    "IDFCFIRSTB": {"name": "IDFC First Bank Limited", "marketCap": "₹0.6L Cr", "pe": 18.5},
    "AUBANK": {"name": "AU Small Finance Bank Limited", "marketCap": "₹0.5L Cr", "pe": 28.5},
    "LTIM": {"name": "LTIMindtree Limited", "marketCap": "₹1.5L Cr", "pe": 38.5},
    "COFORGE": {"name": "Coforge Limited", "marketCap": "₹0.4L Cr", "pe": 45.5},
    "PERSISTENT": {"name": "Persistent Systems Limited", "marketCap": "₹0.6L Cr", "pe": 55.5},
    "DRREDDY": {"name": "Persistent Systems Limited", "marketCap": "₹1.0L Cr", "pe": 22.5},
    "CIPLA": {"name": "Cipla Limited", "marketCap": "₹1.2L Cr", "pe": 32.5},
    "DIVISLAB": {"name": "Cipla Limited", "marketCap": "₹1.0L Cr", "pe": 58.5},
    "BAJAJ-AUTO": {"name": "Bajaj Auto Limited", "marketCap": "₹2.5L Cr", "pe": 32.5},
    "HEROMOTOCO": {"name": "Hero MotoCorp Limited", "marketCap": "₹1.0L Cr", "pe": 26.5},
    "EICHERMOT": {"name": "Eicher Motors Limited", "marketCap": "₹1.3L Cr", "pe": 35.5},
    "M&M": {"name": "Mahindra & Mahindra Limited", "marketCap": "₹2.6L Cr", "pe": 28.5},
    "TVSMOTOR": {"name": "TVS Motor Company Limited", "marketCap": "₹1.1L Cr", "pe": 55.5},
    "DABUR": {"name": "Dabur India Limited", "marketCap": "₹0.9L Cr", "pe": 52.5},
    "GODREJCP": {"name": "Godrej Consumer Products", "marketCap": "₹1.3L Cr", "pe": 65.5},
    "BRITANNIA": {"name": "Britannia Industries Limited", "marketCap": "₹1.2L Cr", "pe": 58.5},
    "MARICO": {"name": "Marico Limited", "marketCap": "₹0.7L Cr", "pe": 48.5},
    "COLPAL": {"name": "Colgate-Palmolive (India)", "marketCap": "₹0.8L Cr", "pe": 55.5},
    "TATAPOWER": {"name": "Tata Power Company Limited", "marketCap": "₹1.3L Cr", "pe": 35.5},
    "ADANIGREEN": {"name": "Adani Green Energy Limited", "marketCap": "₹2.9L Cr", "pe": 155.5},
    "IOC": {"name": "Indian Oil Corporation", "marketCap": "₹2.4L Cr", "pe": 8.5},
    "GAIL": {"name": "GAIL (India) Limited", "marketCap": "₹1.4L Cr", "pe": 12.5},
    "TATASTEEL": {"name": "Tata Steel Limited", "marketCap": "₹2.1L Cr", "pe": 45.5},
    "HINDALCO": {"name": "Hindalco Industries Limited", "marketCap": "₹1.4L Cr", "pe": 18.5},
    "VEDL": {"name": "Vedanta Limited", "marketCap": "₹1.4L Cr", "pe": 15.5},
    "ZOMATO": {"name": "Zomato Limited", "marketCap": "₹1.6L Cr", "pe": 125.5},
    "NAUKRI": {"name": "Info Edge (India) Limited", "marketCap": "₹0.7L Cr", "pe": 85.5},
    "HAL": {"name": "Hindustan Aeronautics Ltd", "marketCap": "₹2.8L Cr", "pe": 42.5},
    "BEL": {"name": "Bharat Electronics Limited", "marketCap": "₹2.1L Cr", "pe": 45.5},
    "IRCTC": {"name": "IRCTC Limited", "marketCap": "₹0.8L Cr", "pe": 65.5},
    "VBL": {"name": "Varun Beverages Limited", "marketCap": "₹2.0L Cr", "pe": 85.5},
    "PIDILITIND": {"name": "Pidilite Industries Limited", "marketCap": "₹1.6L Cr", "pe": 95.5},
    "HAVELLS": {"name": "Havells India Limited", "marketCap": "₹1.1L Cr", "pe": 75.5},
    "SIEMENS": {"name": "Siemens Limited", "marketCap": "₹2.4L Cr", "pe": 95.5},
    "ABB": {"name": "ABB India Limited", "marketCap": "₹1.6L Cr", "pe": 92.5},
    "DLF": {"name": "DLF Limited", "marketCap": "₹2.2L Cr", "pe": 75.5},
}
